#####################################################################
# Select components to install

# Main infra subcomponents
install_kubernetes: true
install_metallb: true

# Install applications addons:
install_addons: true
install_addons_database: true

# Install common infrastructure:
#   kubernetes cluster, CNI, common services
install_infra: true

# Install Pathfinder product
install_northstar: true

# Install Pathfinder netflowd (optional)
install_netflowd: true

# Install Paragon UI
install_paragon_ui: true

# Install Insights product
install_healthbot: true

# Install EMS product
install_ems: true

# Install chrony NTP
install_chrony: true

# NGINX Ingress Controller (used for Pathfinder services, such as netflowd and pceserver)
install_nginx_ingress: true

#####################################################################
# Required configuration values
#
# Configure ethernet interface for cluster internal communication
# Defaults to default-ipv4 interface (i.e. target of default route)
kubernetes_system_interface: '{{ default_interface }}'

# Optionally allow scheduling of application workloads on master node
allow_master_scheduling: true

# LoadBalancer
# List of IP address ranges or prefixes owned by metallb, e.g.:
# metallb_addresses:
#  - 10.0.0.1-10.0.0.20
#  - 10.0.0.192/26
metallb_addresses:
  - 10.0.0.100-10.0.0.101

# alternatively, for metallb in L3 (BGP) mode, enable the following:
# metallb_mode: l3
# metallb_asn: 64500
# metallb_peer_asn: 64501
# metallb_peer_address: 192.168.10.1

# Ports to be checked on system if they are open or not
port_list: 8080 6443 2379 2380 179 10250 8443 7005 80 443 7804 7000 4189 67 514 1114 4000 162 9345

# NTP configuration, configure reachable NTP servers
chrony_config_server:
  - ntp.juniper.net

# Ingress Controller
# service type and LoadBalancer settings
ingress_service_type: LoadBalancer
ingress_service_annotations: {}
# ingress service config to preserve source ip. Valid values are Cluster(default) or Local.
ingress_external_traffic_policy: Local
#  metallb.universe.tf/allow-shared-ip: default

# Fixed IP addresses for Web interface. The addresses must be in a pool
# managed by MetalLB.
ingress_vip:
  - 10.0.0.100

# Fixed IP address for device callback. This must be one of the addresses
# assigned to the ingress controller
callback_vip: 10.0.0.100

# Fixed IPv6 address for device callback. This must be one of the addresses
# assigned to the ingress controller
callback_vip6: ''


#####################################################################
# Pathfinder application configuration

northstar_image_pull_policy: IfNotPresent

# Hostname of Pathfinder web server, must resolve to ingress_vip
northstar_web_hostname: web.example.com

# Virtual IP address of PCEP server. The address must be in a pool managed
# by MetalLB and must be different from ingress_vip
# northstar_pceserver_vip: 10.0.0.2
northstar_pceserver_vip: ''
northstar_pceserver_replicas: 1
northstar_pceserver_proxy: nginx


# multus
install_multus: true
# if not specified multus_interface will be set to kubernetes default interface
multus_interface: ''
multus_bridge_name: macvlan-bridge
# Static route for PCEserver and CRPD to the router
# example:
# multus_routes:
#   - dst: 192.168.1.0/24 
#     gateway: 2.2.2.1
#   - dst: 192.168.2.0/24 
#     gateway: 2.2.2.1  
multus_routes:
  - dst: ''
    gateway: ''


# set to true to enable PCEP MD5
northstar_pceserver_md5_ip: ''
northstar_pceserver_md5_mac: ''


# Virtual IP address of nginx-ingress-controller. The address must be in a pool managed
# by MetalLB and must be different from ingress_vip
# nginx_controller_vip: 10.0.0.2
nginx_controller_vip: 10.0.0.102
nginx_controller_replicas: 1
nginx_service_annotations:
  metallb.universe.tf/allow-shared-ip: nginx-ingress

# northstar/netflowd
# The netflowd service needs to be accessible from outside the cluster. This can be
# accomplished by putting either nginx-ingress in-front of netflowd (default config), with
# northstar_netflowd_proxy: true
# or removing the northstar_netflowd_proxy line
# and configuring the virtual IP address in northstar_netflowd_vip
northstar_netflowd_proxy: true
northstar_netflowd_service_type: ClusterIP
northstar_netflowd_traffic_policy: Local
northstar_netflowd_vip: ''
northstar_netflowd_replicas: 1

# northstar/pcviewer (Pathfinder planner)
# If pcviewer needs to be accessible from outside the cluster, configure
# northstar_pcviewer_service_type: LoadBalancer
# and configure virtual IP address in northstar_pcviewer_vip
northstar_pcviewer_service_type: ClusterIP
northstar_pcviewer_vip: ''

# northstar migration
northstar_db_migration_directory: /var/local/ns_db_migration

# CRPD (BPG-LS peer)
# Use PVC
# crpd_use_pvc: "{{ install_rook }}"
crpd_use_pvc: '{{ install_rook }}'
crpd_pvc_storageclass: rook-cephfs

# Autonomous System number
crpd_autonomous_system: '65000'
# set to true to enable BGP-LS MD5 from cRPDs
crpd_md5_ip: ''
crpd_md5_mac: ''
# BGP md5 authentication key
crpd_auth_key: northstar

# List of BGP neighbors. The BGP neighbors need to be configured to allow
# incoming connections from all nodes in the kubernetes cluster.
# e.g.
#crpd_neighbors:
#  - 10.0.1.1
crpd_neighbors:
  - 10.0.1.1

# Default Web admin password
northstar_web_admin_password: ''

# Optional flag to install debugutils
install_northstar_debugutils: true

# Pathfinder license
northstar_license: |
  expire_date=4/11/2029
  usercount=5
  node_limit=250
  card=micro_service
  MAC=FF:EE:DD:CC:BB:AA
  customer=MICRO_SERVICE
  S-NS-PLNR-BSC=bOEdVhfgeoZLDWZmeSjiQW
  S-NS-PLNR-PRM=BSBdLrfCeUXFLTUGWgjgIa
  S-NS-SDN-BSC=cFWPOomLXkRLDWZmeSjiQW
  S-NS-SDN-STD=bSIbTqUNUbZUUZNETbmWFY
  S-NS-SDN-PRM=JJTSXDWWgVaFEjjRTaFXDW

#####################################################################
# Insights application configuration
#
healthbot_vip: 10.0.0.101
healthbot_service_annotations:
  metallb.universe.tf/allow-shared-ip: default

max_wait: 15

#####################################################################
 Select components  done (4 selections)
? Infrastructure Options  done (5 selections)
? List of NTP servers  ntp.juniper.net
? Virtual IP address(es) for ingress controller  10.219.94.112
? Virtual IP address for Infrastructure Nginx Ingress Controller  10.219.94.113
? Virtual IP address for Insights services  10.219.94.114
? Virtual IP address for SNMP Trap receiver (optional)  .
? Pathfinder Options  [Install Netflowd]
? Use netflowd proxy?  Yes
? PCEServer proxy  Nginx Ingress
? LoadBalancer IP address ranges  10.219.94.112-10.219.94.114
? Enable md5 for PCE Server ?  No
? Enable md5 for BGP ?  No
? Hostname of Main web application  para.example.net
? BGP autonomous system number of CRPD peer  64500
? Comma separated list of CRPD peers  10.219.94.118
